{
    'name': 'Instellars custom fields',
    'version': '13.0.0.26',
    'category': 'Human Resources',
    
    'summary': 'Required custom fields in employee module for instellars',
    'description': "",
    'website': 'https://www.prixgen.com/',
    'depends': [
        'hr',
        'hr_recruitment',
        'hr_skills',
        'base',
        'crm',
        'project',
        'sale',
        'web',
        'hr_payroll',
        'hr_contract',
        'l10n_in_hr_payroll',
    ],
    'data': [
    'data/sequencer.xml',
    'data/mail_templates.xml',
    'data/birthday_wish_cron.xml',
    'data/birthday_wish_template.xml',
    'security/ir.model.access.csv',
    'views/hr_employee_form.xml',
    'views/education.xml',
    'views/res_partner_form_view.xml',
    'views/res_bank.xml',
    'views/hr_recruitment.xml',
    'views/custom_model_views.xml',
    'wizard/skill_rate_card_view.xml',
    'wizard/rise_demand_form.xml',
    'views/project.xml',
    'views/sale_order_form.xml',
    'views/hr_contract.xml',
    # 'views/hr_payslip.xml',
    # 'views/hr_recruitment_stage.xml',
    ],
    
    'installable': True,
    'application': True,
    'auto_install': False
}
